In [34]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [35]:
from dataset import L2ArcticDataset
from model import Model

In [36]:
data = L2ArcticDataset(
    "train",
    "/home/xt0r3-user/cambridge/partii/dissertation/s3prl/data/l2arctic_release_v5.0", 
    "./data"
)

Skipping malformatted TextGrid file: /home/xt0r3-user/cambridge/partii/dissertation/s3prl/data/l2arctic_release_v5.0/YDCK/annotation/arctic_a0272.TextGrid
Skipping malformatted TextGrid file: /home/xt0r3-user/cambridge/partii/dissertation/s3prl/data/l2arctic_release_v5.0/YDCK/annotation/arctic_a0209.TextGrid


In [37]:
data[3]

(tensor([-6.8054e-03, -7.1716e-03, -6.6833e-03,  ...,  7.6294e-04,
          3.0518e-05,  1.2207e-04]),
 tensor([ 0, 12, 35, 12, 42,  0, 23,  9, 39, 45,  1, 48, 40,  3, 34, 43, 12, 36,
         23,  2, 42,  0, 45,  4, 48,  4, 33, 34, 15, 40, 42,  0, 42, 39,  2, 31,
          3, 22, 14,  0,  0]),
 tensor([ 0,  9, 35,  9, 42,  0, 48,  9, 39, 45,  1, 48, 40,  3, 34, 43, 12, 36,
         48,  2, 42,  0, 45,  4, 48,  4, 33, 34, 15, 40, 42,  0, 42, 39,  2, 31,
          3, 22, 14,  0,  0]),
 41,
 41)

In [45]:
import torch
import numpy as np
list(torch.utils.data.Subset(data, np.arange(1, 4)))

[(tensor([0.0179, 0.0180, 0.0183,  ..., 0.0058, 0.0063, 0.0069]),
  tensor([30, 14, 45, 11, 22, 12, 22, 12, 35, 42, 18, 23,  3,  9, 31,  0,  3, 44,
          23,  3, 45,  4, 42, 10,  0,  3, 35, 22, 20, 12, 29,  2, 35,  0, 40, 32,
          39,  3, 20, 12, 36,  0, 30, 12, 34, 40,  9, 33, 28,  0]),
  tensor([30, 14, 45, 11, 22, 12, 22, 12, 35, 42, 18, 23,  3,  9, 31,  0,  3, 44,
          23,  3, 45, 15, 42, 10,  0,  3, 35, 22, 20, 12, 29,  2, 35,  0, 40, 32,
          39,  3, 20, 12, 36, 32, 30, 12, 34, 40,  9, 33, 28,  0]),
  50,
  50),
 (tensor([0.0110, 0.0099, 0.0096,  ..., 0.0204, 0.0207, 0.0198]),
  tensor([47, 18, 34,  3, 40, 42,  0, 40, 33, 14, 37,  0, 30, 14, 10, 31, 22,  0,
           0]),
  tensor([47, 18, 34,  3, 40,  0,  3, 40, 33, 14, 37,  0, 30, 14, 10, 49, 22,  0,
           0]),
  19,
  19),
 (tensor([-6.8054e-03, -7.1716e-03, -6.6833e-03,  ...,  7.6294e-04,
           3.0518e-05,  1.2207e-04]),
  tensor([ 0, 12, 35, 12, 42,  0, 23,  9, 39, 45,  1, 48, 40,  3, 34, 43, 12

In [39]:
loader = torch.utils.data.DataLoader(
    data,
    batch_size=4,  # for bucketing
    shuffle=True,
    num_workers=4,
    drop_last=False,
    pin_memory=True,
    collate_fn=data.collate_fn,
)

In [40]:
for item in loader:
    display(item)
    break

[[tensor([ 3.0518e-05, -6.1035e-05,  9.1553e-05,  ..., -6.1035e-05,
           3.0518e-05, -3.0518e-05]),
  tensor([-0.0018, -0.0016, -0.0019,  ...,  0.0029,  0.0032,  0.0034]),
  tensor([ 0.0027,  0.0020,  0.0017,  ..., -0.0004, -0.0009, -0.0008]),
  tensor([-0.0159, -0.0173, -0.0177,  ...,  0.0074,  0.0064,  0.0066])],
 tensor([[23, 12, 40, 45,  3, 35, 30, 15, 37, 45,  1, 48, 22, 12, 40, 42, 39, 16,
          22,  2, 48, 32, 45, 12, 32, 33, 14,  2, 48, 12, 42, 45,  3, 48, 20,  4,
          39, 35,  0,  0,  0,  0,  0,  0],
         [ 0,  8, 30,  2, 44, 42,  3, 20, 14, 32,  9, 39, 28,  3, 33,  3, 44, 23,
           9, 34,  0,  2, 48, 23, 11, 42, 12, 39, 44,  9, 39, 14, 14, 48,  3, 33,
          14,  0,  0,  0,  0,  0,  0,  0],
         [ 0, 12, 35, 40, 42,  9, 22,  0, 30, 14, 31, 16, 35, 22, 30, 10,  0,  2,
          35, 22, 23, 11, 11, 42, 33,  8, 32, 42, 18, 30,  3, 36, 29, 39, 14, 21,
          12, 33, 22, 39,  3, 35,  0,  0],
         [22, 18, 47, 18, 35, 15, 23,  2, 42, 47, 18,  1

In [41]:
from tqdm import tqdm

In [42]:
for batch_id, (wav_view, *others) in enumerate(tqdm(loader, dynamic_ncols=True, desc='train')):
    display(batch_id)
    display(wav_view)
    display(*others)
    break
    # print(*others)

train:   0%|          | 0/712 [00:00<?, ?it/s]

0

[tensor([-0.0223, -0.0226, -0.0231,  ...,  0.0002,  0.0010,  0.0010]),
 tensor([-0.0007, -0.0016, -0.0027,  ...,  0.0033,  0.0027,  0.0033]),
 tensor([-0.0152, -0.0151, -0.0148,  ..., -0.0209, -0.0210, -0.0210]),
 tensor([-0.0093, -0.0081, -0.0078,  ..., -0.0033, -0.0032, -0.0037])]

tensor([[ 0, 47, 18, 30,  2, 44,  3, 40, 15, 41, 14, 11, 42,  3, 22,  0, 45, 12,
         43, 40,  3, 34,  3, 44, 23, 14, 48, 34,  9, 35,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0, 28, 39, 10,  3, 28, 17, 33, 34, 12, 35,  3, 42, 30, 14, 32, 39,  5,
         21, 42,  2, 35, 22, 33, 12, 40,  3, 35, 22,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0, 22,  9, 43,  0, 30,  2, 22, 32,  3, 34, 45, 12, 23, 42,  9, 39,  3,
         20,  3, 33, 40,  3, 22,  3, 35, 35,  3, 40,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0, 23,  9, 35, 47, 18, 32,  2, 35, 10, 11, 35, 31, 47, 10, 40,  9, 33,
         28,  0, 32,  3, 34, 28, 10, 42,  3, 20, 33, 14,  0,  3, 34,  3, 36, 23,
         14, 48, 39, 15, 20, 48,  0, 12, 35, 23,  3, 20, 15,  0,  0]])

tensor([[ 0, 47, 18, 30,  2, 44,  3, 40, 15, 41, 14, 11, 42,  3, 22,  0, 45, 12,
         40, 40,  3, 34,  3, 44, 22, 14, 40, 34,  9, 35,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0, 28, 39, 10,  3, 28, 17, 33, 34, 12, 35,  3, 42, 30, 14, 32, 39,  2,
         21, 42,  2, 35, 22, 33, 14, 40,  3, 35, 42,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0, 22,  2, 43,  0, 30,  2, 22, 32,  3, 34, 45, 12, 22, 42,  9, 39,  3,
         20,  3, 33, 40,  3, 22,  3, 35, 33,  3, 40,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0, 22,  9, 35, 47, 18, 32,  2, 35, 10, 14, 35, 21, 47, 10, 40,  9, 33,
         28,  0, 32,  3, 34, 28, 10, 42, 20,  3, 33, 14,  0,  3, 34,  3, 35, 22,
         14, 40, 39, 15, 20, 40,  0, 12, 35, 22,  3, 20, 15,  0,  0]])

tensor([32, 31, 31, 51])

tensor([32, 31, 31, 51])

train:   0%|          | 0/712 [00:00<?, ?it/s]


In [43]:
data[400]

(tensor([-0.0026, -0.0026, -0.0024,  ...,  0.0006,  0.0004,  0.0002]),
 tensor([30, 14, 45, 12, 33, 28,  1, 33, 15,  3, 40, 40, 18, 35,  0,  0]),
 tensor([30, 14, 45, 12, 33, 28,  1, 33,  4,  3, 40, 40, 18, 35,  0,  0]),
 16,
 16)

In [44]:
data[3:5]

TypeError: list indices must be integers or slices, not str

In [ ]:
l1_model = Model(
    input_dim=self.upstream_dim,
    output_class_num=self.dataset['train'].output_class_num
    **self.modelrc,